[LOGICALS]
;----------------------------------------
AUD_ENT_LIST=
NBR_RECS_PER_PAGE=10
BASE_URL=
MD5_HASH_PASSWORD=
RUN_ON_SERVER=S
GENERATE_SRL=CLIENT
INSTANCE_NAME=sits
TTQ_ENCODE_BLANK_INPUT_TYPE = N
USERUNPREFIX=F
APPLICATION_TITLE=
WEB_AUTH_USER=REMOTE_USER
TRANSACTION_LOGGING=Y
PROGRAM_ACCESS_LOG=Y
DOCUMENT_GUID=Y
BROWSER_ID_CHECK=MULTI
BROWSER_ID_CALLBACK=N
SELECTION_LIST_MAX=2000
;----------------------------------------
CACHE_FLD=N
CACHE_GET_SRL=N
CACHE_SLP=N
CACHE_SYP=N
CACHE_SSC=N
CACHE_TASK=N
CACHE_TUP=N
PAGETABS_CACHING=N
;----------------------------------------
EMAIL_ON_SERVER = S
EMAIL_WHITELIST=*@example.com
;----------------------------------------
