version: '3'
services:
    oracle:
        image: oracle:sits_990
        ports:
        - "1521:1521"
    sits-app:
        image: sits:app_990
        ports:
        - "13086:13086"
        links:
        - oracle
        - sits-webapp
        - sits-web
    sits-webapp:
        image: sits:webapp_990
        ports:
        - "13084:13084"
        - "13089:13089"
        links:
        - oracle
    sits-web:
        image: sits:web_990
        ports:
        - "80:80"
        links:
        - sits-webapp
