# SITS namespace
kind: Namespace
apiVersion: v1
metadata:
  name: sits
  labels:
    name: sits
---
# Oracle deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: oracle
  namespace: sits
spec:
  selector:
    matchLabels:
      app: oracle
  template:
    metadata:
      labels:
        app: oracle
    spec:
      containers:
        - name: oracle-sits
          image: oracle:sits-9.7.0
---
# Oracle service
apiVersion: v1
kind: Service
metadata:
  name: oracle
  namespace: sits
spec:
  type: NodePort
  ports:
  - port: 1521
    targetPort: 1521
  selector:
    app: oracle
---
# SITS app deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sits-app
  namespace: sits
spec:
  selector:
    matchLabels:
      app: sits-app
  template:
    metadata:
      labels:
        app: sits-app
    spec:
      containers:
        - name: sits-app
          image: sits:9.7.0-app
---
# SITS app service
apiVersion: v1
kind: Service
metadata:
  name: sits-app
  namespace: sits
spec:
  type: NodePort
  ports:
  - port: 13086
    targetPort: 13086
  selector:
    app: sits-app
