[SETTINGS]
$search_descriptor=dbms_first

[FILES]
uqtb*.*   usys:..\components\uqtb*.*
uqtd*.*   usys:uqtd*.*
uqt.chm   usys:..\doc\uqt.chm

[LOGICALS]
UQT_LIST_VIDEO=11
UQT_SMTP_SVR=Server Name
UQT_REPORT_IMAGE1=path\filename.gif or ^glyphname
UQT_REPORT_IMAGE2=path\filename.gif or ^glyphname
UQT_DESIGN_MODE_LIMIT=100
UQT_WORK_FILE_SIZE=50
UQT_OUTPUT_LIMIT=10000
UQT_XML_USED=1
UQT_CHART_USED=1
UQT_CHART_HPOS=35
UQT_CHART_VPOS=35
UQT_CHART_HSIZE=150
UQT_CHART_VSIZE=100
UQT_CHART_FILE_HSIZE=750
UQT_CHART_FILE_VSIZE=450
UQT_CHART_OCX_NAME=OWC10.ChartSpace
UQT_AUTOGEN_NEW_ID=1
UQT_NEW_PREFIX=QUERY
UQT_IMPORT_PREFIX=IMPORT
UQT_PORTRAIT_PRINTER=PORTRAIT
UQT_LANDSCAPE_PRINTER=LANDSCAPE
UQT_SAVE_FILE_PRINTER=FILE
UQT_MAIL_FROM=Email Address
UQT_FILE_PATH=
UQT_WORK_FOLDER=
UQT_WALLPAPER=path\filename.gif or ^glyphname
UQT_VIEWER_HELP_FILE=
UQT_HTML_CHARSET=
UQT_XML_ENCODING=
